### ISSUE TITLE
Anyone have feedback yet for papers/grades?

### ISSUE THREAD

**Issue by kaseympotts** [Watts-College/cpp-524-fall-2021#40]
Has anyone received feedback on their paper, or updated grades? 
Is there an official deadline for re-writes assuming we get feedback?

Asking here before contacting Prof Lecy directly as I know a person's time is finite, and would rather not add to his burden of answering more emails if a fellow student can clear this up.

**Comment by mrowland1** [comment]
@kaseympotts I have not received anything either.

**Comment by MegsBruce** [comment]
Nothing here either.

**Comment by JPRayes** [comment]
I haven't received anything either. It's concerning considering final grades are due 13 DEC.

**Comment by mrowland1** [comment]
Yeah I thought we were supposed to have comments by Tuesday he said. Has anyone contacted him?

**Comment by ebossert** [comment]
I also have not received any feedback or grades and haven't contacted him

**Comment by asukajames** [comment]
I have not received any feedback either. 
I had emailed him last week before I took a final exam and also let him know that I would not be able to take advantage of revising my paper because I would go on vacation. (well I actually am now)
I asked him if I could receive feedback or grades but have not heard back from him :(

**Comment by verogutierrezasu** [comment]
I have not received any feedback either

**Comment by LamiaaZrara** [comment]
Same for me, I have not received any feedback either.

**Comment by danafuller** [comment]
It looks like we are all in the same boat
